import requests
import json
from src.config import settings
import uuid

API_URL = "https://api.creatomate.com/v1/renders"

def start_video_render(plan: dict, source_video_url: str) -> str:
    """
    Starts a video rendering job on Creatomate.

    Args:
        plan: The production plan generated by Gemini.
        source_video_url: The public URL of the source video file.

    Returns:
        The ID of the render job, or None on error.
    """
    if not settings.CREATOMATE_API_KEY or not settings.CREATOMATE_TEMPLATE_ID:
        print("MOCK_CREATOMATE: Pretending to start render job (API key or template ID not set).")
        return f"mock-render-{uuid.uuid4()}"

    headers = {
        "Authorization": f"Bearer {settings.CREATOMATE_API_KEY}",
        "Content-Type": "application/json",
    }

    # This payload is structured for a specific Creatomate template.
    # The template would have dynamic elements named "source_video" and "edits".
    payload = {
        "template_id": settings.CREATOMATE_TEMPLATE_ID,
        "modifications": {
            "source_video": source_video_url,
            # We serialize our clips array into a JSON string to pass to the template
            "edits": json.dumps(plan.get('clips', []))
        }
    }

    try:
        print("Starting Creatomate render job...")
        response = requests.post(API_URL, headers=headers, json=payload)
        response.raise_for_status()

        render_data = response.json()
        # The response is an array, get the first item.
        render_id = render_data[0]['id']
        print(f"✅ Creatomate job started with ID: {render_id}")
        return render_id
    except requests.exceptions.RequestException as e:
        print(f"🚫 Error starting Creatomate render: {e}")
        return None
    except (KeyError, IndexError) as e:
        print(f"🚫 Error parsing Creatomate response: {e}")
        return None

def get_render_status(render_id: str) -> dict:
    """
    Gets the status of a rendering job from Creatomate.

    Args:
        render_id: The ID of the render job to check.

    Returns:
        A dictionary with the status and optionally the output URL.
    """
    if render_id.startswith("mock-render-"):
        print(f"MOCK_CREATOMATE: Pretending to get status for render {render_id}.")
        import random
        if random.random() > 0.3:
            return {"status": "in_progress", "url": None}
        else:
            return {
                "status": "succeeded",
                "url": "https://creatomate.com/files/mock/final_video.mp4"
            }

    if not settings.CREATOMATE_API_KEY:
        return {"status": "failed", "message": "Creatomate API key not configured."}

    headers = {
        "Authorization": f"Bearer {settings.CREATOMATE_API_KEY}",
    }
    status_url = f"{API_URL}/{render_id}"

    try:
        response = requests.get(status_url, headers=headers)
        response.raise_for_status()

        data = response.json()
        return {
            "status": data.get("status"),
            "url": data.get("url") # This will be null until status is 'succeeded'
        }
    except requests.exceptions.RequestException as e:
        print(f"🚫 Error getting Creatomate status: {e}")
        return {"status": "failed", "message": str(e)}
